name: CICD

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Dependencies
        run: npm ci

      - name: Generate Deployment Package
        run: |
          zip -r nodejs-app-build.zip . -x "node_modules/*" ".git/*" ".github/*"

      - name: Deploy to Elastic Beanstalk
        uses: einaregilsson/beanstalk-deploy@v21
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          application_name: 'attendance-tracking'
          environment_name: 'Attendance-tracking-env'
          version_label: 'attendance-${{ github.run_number }}'
          region: us-east-1
          deployment_package: nodejs-app-build.zip
          use_existing_version_if_available: true
